version: '3.9'

services: 
  db:
    container_name: db
    image: postgres:12
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pgdata: {}